# Generated by Django 4.2.6 on 2023-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='Team/picture/%Y/%m/%d')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('picture_2', models.ImageField(blank=True, upload_to='Team/picture_2/%Y/%m/%d')),
                ('name_2', models.CharField(blank=True, max_length=255)),
                ('job_2', models.CharField(blank=True, max_length=255)),
                ('picture_3', models.ImageField(blank=True, upload_to='Team/picture_3/%Y/%m/%d')),
                ('name_3', models.CharField(blank=True, max_length=255)),
                ('job_3', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
    ]
