# Generated by Django 4.2.6 on 2023-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('icons', models.ImageField(blank=True, upload_to='Service/icons/%Y/%m/%d')),
                ('icons_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icons_title_2', models.CharField(blank=True, max_length=255)),
                ('description_2', models.TextField(blank=True)),
                ('icons_title_3', models.CharField(blank=True, max_length=255)),
                ('description_3', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
