# Generated by Django 4.2.6 on 2023-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('text_title', models.CharField(blank=True, max_length=255)),
                ('text_sub_title', models.CharField(blank=True, max_length=255)),
                ('text_description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='About/picture/%Y/%m/%d')),
                ('text_title_2', models.CharField(blank=True, max_length=255)),
                ('text_sub_title_2', models.CharField(blank=True, max_length=255)),
                ('text_description_2', models.TextField(blank=True)),
                ('picture_2', models.ImageField(blank=True, upload_to='About/picture_2/%Y/%m/%d')),
                ('text_title_3', models.CharField(blank=True, max_length=255)),
                ('text_sub_title_3', models.CharField(blank=True, max_length=255)),
                ('text_description_3', models.TextField(blank=True)),
                ('picture_3', models.ImageField(blank=True, upload_to='About/picture_3/%Y/%m/%d')),
                ('text_title_4', models.CharField(blank=True, max_length=255)),
                ('text_sub_title_4', models.CharField(blank=True, max_length=255)),
                ('text_description_4', models.TextField(blank=True)),
                ('picture_4', models.ImageField(blank=True, upload_to='About/picture_4/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
